AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  SAM Template for dynamic build of qvf-generate-scripts
Globals:
  Function:
    Timeout: 60
Resources:
  QvfGenerateScriptsDynamicFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: .
      Handler: qvf-generate-scripts
      Runtime: provided.al2
      MemorySize: 1024
      Events:
        QvfGenerateScripts:
          Type: Api
          Properties:
            Path: /qvf-generate-scripts-dynamic
            Method: get
    Metadata:
      BuildMethod: makefile
Outputs:
  QvfGenerateScriptsDynamicApi:
    Description: API Gateway endpoint URL for Dev stage for QVF Generate Scripts function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/qvf-generate-scripts-dynamic
  QvfGenerateScriptsDynamicFunction:
    Description: QVF Generate Scripts Lambda Function ARN
    Value:
      Fn::GetAtt: [QvfGenerateScriptsDynamicFunction, Arn]

