AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >-
  SAM Template for static build of qvf-generate-scripts
Globals:
  Function:
    Timeout: 30
Resources:
  QvfGenerateScriptsStaticFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Zip
      CodeUri: .
      Handler: qvf-generate-scripts
      Runtime: provided
      Events:
        QvfGenerateScripts:
          Type: Api
          Properties:
            Path: /generate-scripts
            Method: get
    Metadata:
      BuildMethod: makefile
Outputs:
  QvfGenerateScriptsStaticApi:
    Description: API Gateway endpoint URL for Prod stage for QVF Generate Scripts function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  QvfGenerateScriptsStaticFunction:
    Description: QVF Generate Scripts Lambda Function ARN
    Value:
      Fn::GetAtt: [QvfGenerateScriptsStaticFunction, Arn]
  QvfGenerateScriptsFunctionIamRole:
    Description: Implicit IAM Role created for QVF Generate Scripts function
    Value:
      Fn::GetAtt: [QvfGenerateScriptsFunctionRole, Arn]
