version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "QVF-Example-Lambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mgvxtwlz9hav"
s3_prefix = "QVF-Example-Lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
